# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categorias', models.CharField(choices=[('AC', 'Academias'), ('BA', 'Bancos'), ('SA', 'Saude_Medicina'), ('HO', 'Hoteis_Pousadas'), ('OR', 'Organizacoes_Religiosas'), ('BE', 'Beleza'), ('BA', 'Bares_Restaurantes_Lanchonetes'), ('SU', 'Supermercados_Conveniencias'), ('CA', 'Casas_Shows_Eventos'), ('ED', 'Educacao'), ('OT', 'Outros')], max_length=25)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('imagem', models.ImageField(blank=True, upload_to='static/images/postagem')),
            ],
        ),
    ]
