# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('valor_avaliacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categorias', models.CharField(choices=[('Academia', 'Academias'), ('Bancos', 'Bancos'), ('Sa\xfade e Medicina', 'Saude_Medicina'), ('Hoteis e Pousadas', 'Hoteis_Pousadas'), ('Organiza\xe7\xf5es Religiosas', 'Organizacoes_Religiosas'), ('Beleza', 'Beleza'), ('Bares, Restaurantes e Lanchonetes', 'Bares_Restaurantes_Lanchonetes'), ('Supermercados e Conveni\xeancia', 'Supermercados_Conveniencias'), ('Casas de Shows e Eventos', 'Casas_Shows_Eventos'), ('Educa\xe7\xe3o', 'Educacao'), ('Outros', 'Outros')], max_length=40)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('imagem', models.ImageField(blank=True, upload_to='locais/static/images/postagem')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locais.Avaliacao')),
            ],
        ),
    ]
