# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.CharField(choices=[('Academia', 'Academias'), ('Bancos', 'Bancos'), ('Sa\xfade e Medicina', 'Saude_Medicina'), ('Hoteis e Pousadas', 'Hoteis_Pousadas'), ('Organiza\xe7\xf5es Religiosas', 'Organizacoes_Religiosas'), ('Beleza', 'Beleza'), ('Bares, Restaurantes e Lanchonetes', 'Bares_Restaurantes_Lanchonetes'), ('Supermercados e Conveni\xeancia', 'Supermercados_Conveniencias'), ('Casas de Shows e Eventos', 'Casas_Shows_Eventos'), ('Educa\xe7\xe3o', 'Educacao'), ('Outros', 'Outros')], max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='/static/images/postagem'),
        ),
    ]
