# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_auto_20161027_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='locais/static/images/postagem'),
        ),
    ]
