# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='login',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
