# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0005_useradmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
