# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('avaliacao', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('titulo_local', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categorias', models.CharField(choices=[('Academia', 'Academias'), ('Bancos', 'Bancos'), ('Sa\xfade e Medicina', 'Sa\xfade e Medicina'), ('Hoteis e Pousadas', 'Hot\xe9is e Pousadas'), ('Organiza\xe7\xf5es Religiosas', 'Organiza\xe7\xf5es Religiosas'), ('Beleza', 'Beleza'), ('Bares, Restaurantes e Lanchonetes', 'Bares, Restaurantes e Lanchonetes'), ('Supermercados e Conveni\xeancia', 'Supermercados e Conveni\xeancias'), ('Casas de Shows e Eventos', 'Casas de Shows e Eventos'), ('Educa\xe7\xe3o', 'Educa\xe7\xe3o'), ('Outros', 'Outros')], max_length=40)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('imagem', models.ImageField(blank=True, upload_to='locais/static/images/postagem')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='locais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='locais.Post'),
        ),
    ]
