# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_remove_post_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.CharField(choices=[('Academia', 'Academias'), ('Bancos', 'Bancos'), ('Sa\xfade e Medicina', 'Sa\xfade e Medicina'), ('Hoteis e Pousadas', 'Hot\xe9is e Pousadas'), ('Organiza\xe7\xf5es Religiosas', 'Organiza\xe7\xf5es Religiosas'), ('Beleza', 'Beleza'), ('Bares, Restaurantes e Lanchonetes', 'Bares, Restaurantes e Lanchonetes'), ('Supermercados e Conveni\xeancia', 'Supermercados e Conveni\xeancias'), ('Casas de Shows e Eventos', 'Casas de Shows e Eventos'), ('Educa\xe7\xe3o', 'Educa\xe7\xe3o'), ('Outros', 'Outros')], max_length=40),
        ),
    ]
