# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_auto_20161110_1339'),
        ('locais', '0003_auto_20161109_0229'),
    ]

    operations = [
    ]
