# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 01:00
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_merge_20161110_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='local',
            name='longitude',
        ),
        migrations.AddField(
            model_name='local',
            name='position',
            field=geoposition.fields.GeopositionField(default=1, help_text='N\xe3o altere os valores calculados automaticamente de latitude e longitude', max_length=42, verbose_name='Geolocaliza\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
