# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0005_auto_20161122_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='categorias',
            field=models.CharField(choices=[('academia', 'Academias'), ('bancos', 'Bancos'), ('saudemedicina', 'Sa\xfade e Medicina'), ('hoteispousadas', 'Hot\xe9is e Pousadas'), ('religiosas', 'Organiza\xe7\xf5es Religiosas'), ('beleza', 'Beleza'), ('barrestlanch', 'Bar, Restaurantes e Lanchonetes'), ('superconv', 'Supermercados e Conveni\xeancias'), ('casashoweventos', 'Casas de Shows e Eventos'), ('educacao', 'Educa\xe7\xe3o'), ('outros', 'Outros')], max_length=40),
        ),
        migrations.AlterField(
            model_name='local',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='locais/images/'),
        ),
        migrations.AlterField(
            model_name='local',
            name='position',
            field=geoposition.fields.GeopositionField(default='-6.8078347, -35.07674689999999', help_text='N\xe3o altere os valores calculados automaticamente de latitude e longitude', max_length=42, verbose_name='Geolocaliza\xe7\xe3o'),
        ),
    ]
